services:
  bitcoin:
    build:
      context: ./bitcoin/docker
      dockerfile: Dockerfile
    image: bitcoin:latest
    container_name: bitcoin-core
    restart: unless-stopped
    ports:
      - "8332:8332"   # RPC port
      - "8333:8333"   # P2P port
      - "18332:18332" # Testnet RPC port
      - "18333:18333" # Testnet P2P port
    volumes:
      - bitcoin-data:/data
      - ./bitcoin/bitcoin.conf:/data/bitcoin.conf:ro
    environment:
      - BITCOIN_DATA=/data
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-bitcoinrpc}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_NETWORK=${BITCOIN_NETWORK:-mainnet}
    # user: "1000:1000"  # Commented out to avoid permission issues
    command: [
      "bitcoind", 
      "-datadir=/data", 
      "-printtoconsole", 
      "-server=1",
      "-rpcuser=${BITCOIN_RPC_USER:-bitcoinrpc}",
      "-rpcpassword=${BITCOIN_RPC_PASSWORD}",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=0.0.0.0:8332"
    ]
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data", "-rpcuser=${BITCOIN_RPC_USER:-bitcoinrpc}", "-rpcpassword=${BITCOIN_RPC_PASSWORD}", "-getinfo"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 120s  # Give more time for initial startup
    networks:
      - bitcoin-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${BITCOIN_MEMORY_LIMIT:-16g}
          cpus: '${BITCOIN_CPU_LIMIT:-4.0}'
        reservations:
          memory: 4g
          cpus: '2.0'

  fractal-bitcoin:
    build:
      context: ./fractal-bitcoin/docker
      dockerfile: Dockerfile
    image: fractal-bitcoin:latest
    container_name: fractal-bitcoin-core
    restart: unless-stopped
    ports:
      - "8434:8434"   # Fractal RPC port
      - "8435:8435"   # Fractal P2P port
    volumes:
      - fractal-data:/data
      - ./fractal-bitcoin/fractal.conf:/data/fractal.conf:ro
    environment:
      - FRACTAL_DATA=/data
      - FRACTAL_RPC_USER=${FRACTAL_RPC_USER:-fractalrpc}
      - FRACTAL_RPC_PASSWORD=${FRACTAL_RPC_PASSWORD}
    command: [
      "bitcoind",
      "-datadir=/data",
      "-printtoconsole",
      "-server=1",
      "-rpcuser=${FRACTAL_RPC_USER:-fractalrpc}",
      "-rpcpassword=${FRACTAL_RPC_PASSWORD}",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=0.0.0.0:8434",
      "-port=8435"
    ]
    networks:
      - bitcoin-network

networks:
  bitcoin-network:
    driver: bridge
    # Automatic IP assignment to avoid conflicts
    driver_opts:
      com.docker.network.bridge.name: bitcoin-br0

volumes:
  bitcoin-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/bitcoin/data

  fractal-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/fractal-bitcoin/data