services:
  bitcoin:
    build:
      context: ./bitcoin/docker
      dockerfile: Dockerfile
    image: bitcoin:latest
    container_name: bitcoin-core
    restart: unless-stopped
    ports:
      - "8332:8332"   # RPC port
      - "8333:8333"   # P2P port
      - "18332:18332" # Testnet RPC port
      - "18333:18333" # Testnet P2P port
    volumes:
      - bitcoin-data:/data
      - ./bitcoin/bitcoin.conf:/data/bitcoin.conf:ro
    environment:
      - BITCOIN_DATA=/data
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-bitcoinrpc}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_NETWORK=${BITCOIN_NETWORK:-mainnet}
    # user: "1000:1000"  # Commented out to avoid permission issues
    command: [
      "bitcoind", 
      "-datadir=/data", 
      "-printtoconsole", 
      "-server=1",
      "-rpcuser=${BITCOIN_RPC_USER:-bitcoinrpc}",
      "-rpcpassword=${BITCOIN_RPC_PASSWORD}",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=0.0.0.0:8332"
    ]
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data", "-rpcuser=${BITCOIN_RPC_USER:-bitcoinrpc}", "-rpcpassword=${BITCOIN_RPC_PASSWORD}", "-getinfo"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 120s  # Give more time for initial startup
    networks:
      - bitcoin-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${BITCOIN_MEMORY_LIMIT:-16g}
          cpus: '${BITCOIN_CPU_LIMIT:-4.0}'
        reservations:
          memory: 4g
          cpus: '2.0'

  electrs:
    build:
      context: ./electrs
      dockerfile: Dockerfile
    image: electrs:latest
    container_name: electrum-server
    restart: unless-stopped
    ports:
      - "50001:50001"  # Electrum protocol port
      - "4224:4224"    # Monitoring port
    volumes:
      - electrs-data:/data
      - bitcoin-data:/bitcoin-ro:ro
    environment:
      - RUST_BACKTRACE=1
      - ELECTRS_LOG_LEVEL=${ELECTRS_LOG_LEVEL:-INFO}
      - ELECTRS_DB_DIR=/data
      - ELECTRS_DAEMON_DIR=/bitcoin-ro
      - ELECTRS_DAEMON_P2P_ADDR=bitcoin:8333
      - ELECTRS_DAEMON_RPC_ADDR=bitcoin:8332
      - ELECTRS_DAEMON_RPC_USER=${BITCOIN_RPC_USER:-bitcoinrpc}
      - ELECTRS_DAEMON_RPC_PASS=${BITCOIN_RPC_PASSWORD}
      - ELECTRS_ELECTRUM_RPC_ADDR=0.0.0.0:50001
      - ELECTRS_MONITORING_ADDR=0.0.0.0:4224
      - ELECTRS_VERBOSITY=${ELECTRS_VERBOSITY:-2}
      - ELECTRS_NETWORK=${BITCOIN_NETWORK:-mainnet}
    # user: "1000:1000"  # Commented out to avoid permission issues
    depends_on:
      bitcoin:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4224/metrics"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 180s  # Electrs takes longer to start
    networks:
      - bitcoin-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${ELECTRS_MEMORY_LIMIT:-8g}
          cpus: '${ELECTRS_CPU_LIMIT:-2.0}'
        reservations:
          memory: 2g
          cpus: '1.0'

networks:
  bitcoin-network:
    driver: bridge
    # Automatic IP assignment to avoid conflicts
    driver_opts:
      com.docker.network.bridge.name: bitcoin-br0

volumes:
  bitcoin-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/bitcoin/data
  
  electrs-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/electrs/data