services:
  bitcoin:
    build:
      context: ./bitcoin/docker
      dockerfile: Dockerfile
    container_name: bitcoin-core-test
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - bitcoin-data:/data
    environment:
      - BITCOIN_DATA=/data
    command: [
      "bitcoind", 
      "-datadir=/data", 
      "-printtoconsole", 
      "-server=1",
      "-rpcuser=bitcoinrpc",
      "-rpcpassword=testpassword123",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=0.0.0.0:8332"
    ]
    networks:
      - bitcoin-network

networks:
  bitcoin-network:
    driver: bridge

volumes:
  bitcoin-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/bitcoin/data
