services:
  bitcoin:
    build:
      context: ./bitcoin/docker
      dockerfile: Dockerfile
    image: bitcoin:latest
    container_name: bitcoin-core
    restart: unless-stopped
    ports:
      - "8332:8332"   # RPC port
      - "8333:8333"   # P2P port
      - "18332:18332" # Testnet RPC port
      - "18333:18333" # Testnet P2P port
    volumes:
      - bitcoin-data:/data
      - ./bitcoin/bitcoin.conf:/data/bitcoin.conf:ro
    environment:
      - BITCOIN_DATA=/data
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-bitcoinrpc}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_NETWORK=${BITCOIN_NETWORK:-mainnet}
    command: [
      "bitcoind", 
      "-datadir=/data", 
      "-printtoconsole", 
      "-server=1",
      "-rpcuser=${BITCOIN_RPC_USER:-bitcoinrpc}",
      "-rpcpassword=${BITCOIN_RPC_PASSWORD}"
    ]
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data", "-rpcuser=${BITCOIN_RPC_USER:-bitcoinrpc}", "-rpcpassword=${BITCOIN_RPC_PASSWORD}", "-getinfo"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - bitcoin-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${BITCOIN_MEMORY_LIMIT:-8g}
        reservations:
          memory: 2g

  electrs:
    build:
      context: ./electrs
      dockerfile: Dockerfile
    image: electrs:latest
    container_name: electrum-server
    restart: unless-stopped
    ports:
      - "50001:50001"  # Electrum protocol port
      - "4224:4224"    # Monitoring port
    volumes:
      - electrs-data:/data
      - bitcoin-data:/bitcoin-ro:ro
    environment:
      - RUST_BACKTRACE=1
      - ELECTRS_LOG_LEVEL=${ELECTRS_LOG_LEVEL:-INFO}
      - ELECTRS_DB_DIR=/data
      - ELECTRS_DAEMON_DIR=/bitcoin-ro
      - ELECTRS_DAEMON_P2P_ADDR=bitcoin:8333
      - ELECTRS_DAEMON_RPC_ADDR=bitcoin:8332
      - ELECTRS_DAEMON_RPC_USER=${BITCOIN_RPC_USER:-bitcoinrpc}
      - ELECTRS_DAEMON_RPC_PASS=${BITCOIN_RPC_PASSWORD}
      - ELECTRS_ELECTRUM_RPC_ADDR=0.0.0.0:50001
      - ELECTRS_MONITORING_ADDR=0.0.0.0:4224
      - ELECTRS_VERBOSITY=${ELECTRS_VERBOSITY:-2}
    depends_on:
      bitcoin:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4224/metrics"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - bitcoin-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${ELECTRS_MEMORY_LIMIT:-4g}
        reservations:
          memory: 1g

networks:
  bitcoin-network:
    driver: bridge
    # Let Docker automatically assign IP range to avoid conflicts

volumes:
  bitcoin-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/bitcoin/data
  electrs-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/electrs/data

# Environment configuration
# Create a .env file in the root directory with the following variables:
# BITCOIN_NETWORK=mainnet
# BITCOIN_RPC_USER=bitcoinrpc
# BITCOIN_RPC_PASSWORD=your-secure-password
# BITCOIN_MEMORY_LIMIT=8g
# ELECTRS_MEMORY_LIMIT=4g
# ELECTRS_LOG_LEVEL=INFO
# ELECTRS_VERBOSITY=2